### PR TITLE
Disentangle the Frontend and the Backend

### PR DESCRIPTION
**Pull request by TheMrSheldon**

### CODE REVIEW

**Comment by mam10eks** [comment]
Hi, thank you very much, I likely can only look into this after the upcoming CLEF deadlines.

I saw that some checks are not successfull, could you have a loo what this is? I saw something failed with `jest: not found` which is used for unit tests in the JS code, so maybe they dont run anymore because they dependent on some directory structure?

**Comment by TheMrSheldon** [comment]
The PR is still a draft and under active development

**Comment by mam10eks** [comment]
Ah, alright, thanks for the clarification :)

**Comment by TheMrSheldon** [comment]
The checks are now passing but there are two outstanding todos:

- [ ] Add deployment workflow for the frontend
  - [ ] Deploy as a static site via GitHub pages (this will be configured for the official TIRA deployment by webis)
  - [ ] Create a configurable Docker container and push it to GHCR
- [ ] Add deployment workflow for the backend

The latter (backend deployment workflow) is a lot more complex and should be a separate issue.

**Review by mam10eks — APPROVED** [review]
Looks all good, thanks!

**Pull request merged**
